descriptor-schema-version: "2.10"

info:
  name: AP-WEB-APP
  description: "AP Web App for Cisco Live 2026"
  version: "1.0.0"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"

app:
 # Refer Platform Support Matrix table.
 # armv7l for 32 bit CPU Architecture.
 # aarch64 for 64 bit CPU Architecture.
  cpuarch: aarch64
  type: docker
  resources:
    profile: c1.small
    network:
    - interface-name: eth0
      ports:
        tcp: [8000]
        udp: [8000]

  # Define the root filesystem (rootfs.img) and target command to start the app.
  startup:
    rootfs: rootfs.img
    target: "python3 /main.py"
    workdir: /
    #os-mode: true
